export const GET_STATEMENT_LIST = 'GET_STATEMENT_LIST';
export const GET_STATEMENT_TYPE = 'GET_STATEMENT_TYPE';
export const SET_COMPANY_INFO = 'SET_COMPANY_INFO';

export const FETCH_TABLE_DATA_START = 'FETCH_TABLE_DATA_START';
export const FETCH_TABLE_DATA_SUCCESS = 'FETCH_TABLE_DATA_SUCCESS';
export const FETCH_TABLE_DATA_ERROR = 'FETCH_TABLE_DATA_ERROR';

